# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f70b4e2e32f619b66cd7959a4e794ae7adad75ff9765c5aae68fb893be56586e9c58d9218e959be6be5ba187ae5630c9c023277ead10ea7259636524248718e

test:
  secret_key_base: 2a9f72b0fedfa041901fb71b1dffadb2cf18ced94bcfd798336c447cfacdf923f9ff123cd916849adb6eb7d31fc28ac69db894dc24a0d1005bef886a26a7aaba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
