# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c5464425f38d2b6a14e01aa61c58d54b3724a30198af1c032ec8d69e36037740cbd97db46585a823f3cc58eb259627c1f9871adba317afad180d8fd2b89975

test:
  secret_key_base: 608891e359eca908034ba9418ec1a54756716f7c021dfc8a452e7e3127259a3dec07905a5f071c565d4e3ffce5cfcab65a32f2629cc8e5daa432580bce824167

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
