# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afd90828d6ac0b41df8ffc263d018c871771ed8a32e7e50c8b9a89825d651d250af889b9744d375e855f324592225479112da463a65e54e84a5805fc6785f15c

test:
  secret_key_base: 501de5226f031e83ccd7a778cf98451f671da7cde340c1cf01235dc7fc5aefca4c07f4196393b2771c0e52905c0d3f5bbeb974fc557f83e3e8d0d71e595a5d2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
